### ISSUE TITLE
Feature Request: Multi-Level YAML Tags

### ISSUE THREAD

**Issue by diaovidiu** [pyrochlore/obsidian-tracker#235] opened 2023-07-26 12:26 UTC
Hi,

first of all, i do appreciate your great work with this tracker. 

I was just trying to implement a tracker based on my YAML tags. However, my tags are on two levels
<img width="194" alt="image" src="https://github.com/pyrochlore/obsidian-tracker/assets/44063108/83c0778e-3af3-401f-9142-bd43128985a9">

So, would it be possible to plot a chart based on one of the tags within the Habits parent tag?
i.e. for Steps, or of Meditation?

thank you!

**Comment by demig00d** [comment] 2023-08-17 01:16
@diaovidiu, use a dot to refer to a nested value, here is an example: https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestFrontmatter.md#deep-values

**Comment by diaovidiu** [comment] 2023-08-17 06:44
Thank you @demig00d for your reply.

For i don't know what reason, this is NOT working for me.
Above the structure I have in the daily notes and below, the code i'm using and the error i get.
<img width="342" alt="image" src="https://github.com/pyrochlore/obsidian-tracker/assets/44063108/3a4fb071-f0fc-4567-9be0-082f53a786a2">

<img width="304" alt="image" src="https://github.com/pyrochlore/obsidian-tracker/assets/44063108/f675c710-d64b-41d4-af79-0ef86bee767c">

**Comment by demig00d** [comment] 2023-08-17 09:31
> I was just trying to implement a tracker based on my YAML tags. However, my tags are on two levels <img alt="image" width="194" src="https://user-images.githubusercontent.com/44063108/256229637-83c0778e-3af3-401f-9142-bd43128985a9.png">

Oh, I missed that you are trying to use booleans as values, there is a known limitation on this https://github.com/pyrochlore/obsidian-tracker/issues/79#issuecomment-948460235, try replacing them with 1 and 0 in your frontmatter.

If the error still occurs, post the frontmatter and query as text here inside the code blocks to make it easier to reproduce.

**Comment by ianscottknight** [comment] 2023-10-26 07:09
The same problem is happening to me. 

<img width="314" alt="Screenshot 2023-10-26 at 00 08 40" src="https://github.com/pyrochlore/obsidian-tracker/assets/25094252/e2b294bd-860e-4ce2-a8a8-3a15234df34f">

<img width="366" alt="Screenshot 2023-10-26 at 00 08 17" src="https://github.com/pyrochlore/obsidian-tracker/assets/25094252/5215e17c-422b-420f-a7d9-86d844a49cd0">

<img width="312" alt="Screenshot 2023-10-26 at 00 09 18" src="https://github.com/pyrochlore/obsidian-tracker/assets/25094252/271625b3-1af7-4cf3-8c52-d0b2cda6e987">

**Comment by diaovidiu** [comment] 2023-10-26 16:24
in the end, it worked for me with the dot notation. But, be aware, the same error you might get for different other reasons: i.e. not finding the folder you mentioned, or not finding any data in the folder mentioned. 
mind the lowe/capital case as well.

So, check if indeed the folder you are having the daily notes is "Periodic Notes/Daily" or "Periodic/Daily" or "periodic/daily" etc

**Comment by ianscottknight** [comment] 2023-10-26 17:51
> in the end, it worked for me with the dot notation. But, be aware, the same error you might get for different other reasons: i.e. not finding the folder you mentioned, or not finding any data in the folder mentioned. mind the lowe/capital case as well.
> 
> So, check if indeed the folder you are having the daily notes is "Periodic Notes/Daily" or "Periodic/Daily" or "periodic/daily" etc

Interesting. I confirmed that the folder is correct. Moreover, when I change to using unnested frontmatter in the periodic file and in the tracker code block, the calendar appears as expected. So it is indeed the frontmatter nesting that is the issue for me.

**Comment by lazyguru** [comment] 2023-11-06 03:15
Closing as original poster stated problem was resolved for them. If someone else is still having an issue, please try updating to the latest release (just released earlier today 1.11.0) and see if the issue still persists. If so, please open a new issue providing a dataview search and example files.

**Closed by lazyguru** 2023-11-06 03:15 UTC

**Comment by certainlyNotHeisenberg** [comment] 2024-01-13 23:55
> in the end, it worked for me with the dot notation

@diaovidiu How did you get it to work? I'm trying to use dot notation but not having any luck. 

For example, I have frontmatter
```
---
sleep:
	quality: 3
---
```
in a note in my `Periodic/Daily` folder. And I have a tracker
```
searchType: frontmatter
searchTarget: sleep.quality
folder: Periodic/Daily
ignoreZeroValue: true
dateFormat: YYYY-MM-DD
startDate: -1w
line:
	xAxisLabel: Day
	xAxisTickLabelFormat: dd
	yAxisLabel: Sleep Quality
	yAxisUnit: 1-5
	yAxisTickLabelFormat: i
	yAxisTickInterval: 1
	yMax: 5.5
	yMin: 0
	fillGap: true
```
But I get a "no valid Y value" error.

I've confirmed that the same tracker works if the frontmatter is formatted as
```
---
sleep-quality: 3
---
```
and the tracker as
```
searchType: frontmatter
searchTarget: sleep-quality
folder: Periodic/Daily
ignoreZeroValue: true
dateFormat: YYYY-MM-DD
startDate: -1w
line:
	xAxisLabel: Day
	xAxisTickLabelFormat: dd
	yAxisLabel: Sleep Quality
	yAxisUnit: 1-5
	yAxisTickLabelFormat: i
	yAxisTickInterval: 1
	yMax: 5.5
	yMin: 0
	fillGap: true
```
So it seems that I can't reference nested frontmatter. But you said you got it to work?

**Comment by sahilarora535** [comment] 2024-02-16 08:51
+1, facing the exact same issue, the frontmatter and tracker don't work as expected when frontmatter is nested YAML:

Frontmatter:

```
---
habit.waterIntake: 2
---
```

Tracker (doesn't work):

```tracker
searchType: tag
searchTarget: habit.waterIntake
line:
  title: Water Intake
```

if I change the tracker type to `text`, it works perfectly:

```tracker
searchType: text
searchTarget: habit.waterIntake
line:
  title: Water Intake
```

Looks like an issue with parsing nested YAML.
