### ISSUE TITLE
Invalid date range?

### ISSUE THREAD

**Issue by fipeop** [pyrochlore/obsidian-tracker#14] opened 2021-05-11 03:46 UTC
I keep seeing the message 'invalid date range'. What am I doing wrong? I already set the date format to YYYY-MM-DD_ddd and the journal folder in the plugin settings. Thank you!

``` tracker
searchType: tag
searchTarget: #🔥/learn  
folder: /
startDate: 2021-05-08_Sat
endDate: 2021-05-10_Mon
line:
    title: "Line Chart"
    xAxisLabel: Date
    yAxisLabel: Value
```

**Comment by pyrochlore** [comment] 2021-05-11 04:39
Please place a parameter ‘dateFormat’ to fit your settings.
Or set the format in plugin’s setting panel.

**Comment by pyrochlore** [comment] 2021-05-11 07:49
Hi, I found where the problem is.
Please remove the sharp character '#' in your searchTarget, it is a special character for YAML (stands for comment).

The error message is wrong. I will fix it in the next version.

**Comment by pyrochlore** [comment] 2021-05-12 14:09
The error message has been corrected in the new released version 1.4.1.
Now it will show 'Invalid search target (searchTarget)' for this condition.

**Comment by fipeop** [comment] 2021-05-12 14:26
Thank you for the great work!

**Comment by pyrochlore** [comment] 2021-05-13 00:11
Thanks for the feedback. 
Will close this issue.

**Closed by pyrochlore** 2021-05-13 00:11 UTC
Labels: bug
