### ISSUE TITLE
Unable to read value in searchType: dvField while using symbol like euro (€)

### ISSUE THREAD

**Issue by sotostzam** [pyrochlore/obsidian-tracker#84] opened 2021-11-01 16:52 UTC
When trying to read a value from a dvField that contains a symbol like euro, it is unable to read it.
For example "Bike:: 25€" returns an error "No valid Y value found in notes",
while "Bike:: 25 Euro" works just fine.

**Comment by pyrochlore** [comment] 2021-11-02 06:28
It is caused by the unicode character not included in the search pattern.
Will fix it.

Thanks for the report.

**Comment by pyrochlore** [comment] 2022-02-23 12:16
Unicode characters like these now can be used in `dvField` in release v1.10.9.
Will close this issue.

**Closed by pyrochlore** 2022-02-23 12:16 UTC
Labels: bug
