### ISSUE TITLE
Blank note with Month trackers

### ISSUE THREAD

**Issue by jpmoo** [pyrochlore/obsidian-tracker#52] opened 2021-08-22 16:04 UTC
I'm on Obsidian v 0.12.13 on MacOS and the code below is rendering a blank page in preview no matter what theme I use. It worked fine until that last plugin update (v 1.10.1), and also still works fine with that plugin version on iOS mobile app (v 1.0.4). The code is meant render three month trackers on separate tags (each with a numeric value) in my daily notes.

Any thoughts?

---

```tracker
searchType: tag
searchTarget: slept
datasetName: Sleep
folder: /Dailies
month:
    startWeekOn: 'Sun'
	showStreak: false
    color: purple
    headerMonthColor: purple
    dimNotInMonth: false
    todayRingColor: yellow
    circleColorByValue: true
	selectedRingColor: white
    showSelectedValue: true
```

```tracker
searchType: tag
searchTarget: mood
datasetName: Mood
folder: /Dailies
month:
    startWeekOn: 'Sun'
	showStreak: false
    color: darkred
    headerMonthColor: darkred
    dimNotInMonth: false
    todayRingColor: yellow
	selectedRingColor: white
    circleColorByValue: true
    showSelectedValue: true
```

```tracker
searchType: tag
searchTarget: water
datasetName: Water
folder: /Dailies
month:
    startWeekOn: 'Sun'
	showStreak: false
    color: blue
    headerMonthColor: blue
    dimNotInMonth: false
    todayRingColor: yellow
	selectedRingColor: white
    circleColorByValue: true
    showSelectedValue: true
```

**Comment by pyrochlore** [comment] 2021-08-22 16:51
Hi @jpmoo,
Do you mean this (blank page) happened after you update Tracker to  1.10.1?

**Comment by jpmoo** [comment] 2021-08-22 17:01
Yes, as far as I can tell it happened after updating plug-in to latest version on MacOS. Prior version of plug-in worked fine on MacOS. 

Latest version of plug-in also updated on iOS app, and works fine there.

**Comment by pyrochlore** [comment] 2021-08-22 17:03
Thanks for the report.
I’ll do some tests on Mac and let you know what I found.

**Comment by pyrochlore** [comment] 2021-08-23 02:10
@jpmoo What is the version of the MacOS you are using?
I have Big Sur version 11.4 running fine with Obsidian v0.12.13 and Tracker 1.10.1.

<img width="862" alt="Screen Shot 2021-08-23 at 10 08 09 AM" src="https://user-images.githubusercontent.com/3617615/130380616-f419e974-835a-4213-80f2-6dad6cf48dbb.png">

**Comment by pyrochlore** [comment] 2021-08-23 02:18
[Here](https://drive.google.com/file/d/1GwnaZezDpHLa-tGS5gyBeRYEFN6nOL_1/view?usp=sharing) is the example file for the image above.
Please also download it and try if it works or not.

**Comment by jpmoo** [comment] 2021-08-23 17:23
See below for a screenshot of what I get with your sample file. Blank screen, without any error messages, as if the plugin isn't even loading.

I'm getting errors in the console that seem to corroborate this. See second screenshot below.

Works absolutely fine on my phone in the mobile app.

<img width="1375" alt="Screen Shot 2021-08-23 at 1 18 53 PM" src="https://user-images.githubusercontent.com/25722735/130489871-e83c1520-a81c-473b-875d-4e7624c24b63.png">

<img width="1552" alt="Screen Shot 2021-08-23 at 1 22 40 PM" src="https://user-images.githubusercontent.com/25722735/130490139-3527d9e1-300d-4ce7-a461-fb8849afa530.png">

**Comment by pyrochlore** [comment] 2021-08-23 17:33
Looks like the problem is from the JavaScript function replaceAll.
An old browser might have this kind of issue.
Will fix it. Sorry for the inconvience.

**Comment by pyrochlore** [comment] 2021-08-24 00:32
Hi @jpmoo,

 Do you mind do a test for me? I have done the modification but my Mac cannot repeat the issue.

 I have a temp version with a modified file [here](https://drive.google.com/file/d/12QocFb4ZzIp-qtYK1xVbyfHWjqtMNq-L/view?usp=sharing).
Please  download it and replace the main.js file in folder {your vault}/.obsidian/plugins/obsidian-tracker/
Reopen your vault and see if it works or not.

**Comment by jpmoo** [comment] 2021-08-24 01:29
That works!!

**Comment by pyrochlore** [comment] 2021-08-24 01:48
Will release it soon.

**Comment by pyrochlore** [comment] 2021-08-25 05:39
I will close the issue. 
Welcome to report if you find anything weird.

**Closed** 2021-08-25 05:39 UTC
Labels: bug
