### ISSUE TITLE
error parsing yaml for dataview fields

### ISSUE THREAD

**Issue by Elizabethcase** [pyrochlore/obsidian-tracker#90] opened 2021-11-16 15:46 UTC
I've been loving tracker. It was working really well until the most recent update (I think?). I didn't change any of the calls but all dvField trackers have stopped working for me.

```tracker
searchType: dvField
searchTarget: WordCount
folder: notes/2021/11November/
datasetName: Word Count
month: 
	mode: circle
	threshold: 500
	color: Goldenrod
	circleColorByValue: True
```

```tracker
searchType: dvField
searchTarget: Hours of sleep, Mood, FeelingRested
folder: notes/2021/10October/
datasetName: Hours of Sleep, Mood, Feeling Rested
line: 
	title: Sleep and Mood
	pointColor: lightblue, gold, purple
	showLine: false
	showLegend: true
```

I have dataview fields in every file as `WordCount:: `, `Hours of sleep:: ` etc.

**Comment by pyrochlore** [comment] 2021-11-17 12:45
Hi @Elizabethcase,

Please replace all the 'tabs' by 'spaces' in your code blocks.
This is caused by the underlying functions in Obsidian changed. 
I will do the replacement automatically in the next release.

**Comment by Elizabethcase** [comment] 2021-11-17 17:28
works for me. thanks!

**Comment by pyrochlore** [comment] 2021-11-27 07:56
Will close this issue since it was resolved.

**Closed by pyrochlore** 2021-11-27 07:56 UTC

**Comment by wenlzhang** [comment] 2021-12-04 11:38
Although one can manually replace all "tabs" with "spaces" in tracker blocks, it would default to "tabs" when hitting "Enter" to go to a new line in the code block. This can be a little not convenient when creating tracker code blocks. Is there a workaround for this?
